import { useState } from 'react';
import { Brain, CheckCircle2, ArrowRight, BookOpen, Copy, Check } from 'lucide-react';
import type { AnalysisResult } from '../hooks/useHeatAnalysis';

interface AIRecommendationProps {
  result: AnalysisResult;
}

export function AIRecommendation({ result }: AIRecommendationProps) {
  const { riskLevel, riskLabel, explanation, precautions, recommendedAlternatives, citations } = result;
  const [copied, setCopied] = useState(false);

  // ── Copy Guidance handler ─────────────────────────────────────────────────
  const handleCopy = async () => {
    const text = [
      `HeatShield Risk Assessment`,
      `Risk Level: ${riskLevel}/4 — ${riskLabel}`,
      ``,
      `Analysis:`,
      explanation,
      ``,
      `Precautions:`,
      ...precautions.map((p, i) => `${i + 1}. ${p}`),
      ``,
      `Safer Alternatives:`,
      ...recommendedAlternatives.map((a) => `• ${a}`),
      ``,
      `Sources: ${citations.map((c) => c.source).join(', ')}`,
      ``,
      `Generated by HeatShield — a deterministic heat-risk calculator.`,
      `Not a medical device. Consult a healthcare professional in emergencies.`,
    ].join('\n');

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Silently fail — clipboard not available in all contexts
    }
  };

  return (
    <div className="space-y-4">
      {/* ── Explanation ── */}
      <div className="bg-white rounded-2xl p-5 border border-orange-100 shadow-sm shadow-orange-900/5">
        <div className="flex items-center justify-between mb-3">
          <h3 className="flex items-center gap-2 text-sm font-semibold text-stone-500 uppercase tracking-wide">
            <Brain size={15} className="text-orange-500" />
            AI Analysis
          </h3>
          {/* Copy Guidance button */}
          <button
            id="copy-guidance-btn"
            type="button"
            onClick={handleCopy}
            className={`flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg border transition-all ${
              copied
                ? 'bg-emerald-50 border-emerald-200 text-emerald-700'
                : 'bg-orange-50 border-orange-200 text-orange-600 hover:bg-orange-100'
            }`}
          >
            {copied ? (
              <><Check size={12} /> Copied!</>
            ) : (
              <><Copy size={12} /> Copy Guidance</>
            )}
          </button>
        </div>
        <p className="text-stone-700 leading-relaxed">{explanation}</p>
        <div className="mt-3 flex items-center gap-1.5 text-xs text-stone-400">
          <BookOpen size={12} />
          Grounded in {citations.length} authoritative source{citations.length !== 1 ? 's' : ''}
        </div>
      </div>

      {/* ── Precautions ── */}
      <div className="bg-white rounded-2xl p-5 border border-orange-100 shadow-sm shadow-orange-900/5">
        <h3 className="flex items-center gap-2 text-sm font-semibold text-stone-500 mb-3 uppercase tracking-wide">
          <CheckCircle2 size={15} className="text-emerald-600" />
          Precautions
        </h3>
        <ul className="space-y-2.5">
          {precautions.map((p, i) => (
            <li key={i} className="flex items-start gap-3">
              <span className="mt-0.5 flex-shrink-0 w-5 h-5 rounded-full bg-emerald-100 border border-emerald-200 flex items-center justify-center text-emerald-700 text-xs font-bold">
                {i + 1}
              </span>
              <span className="text-stone-700 text-sm leading-relaxed">{p}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* ── Alternatives ── */}
      <div className="bg-white rounded-2xl p-5 border border-orange-100 shadow-sm shadow-orange-900/5">
        <h3 className="flex items-center gap-2 text-sm font-semibold text-stone-500 mb-3 uppercase tracking-wide">
          <ArrowRight size={15} className="text-orange-500" />
          Safer Alternatives
        </h3>
        <ul className="space-y-2">
          {recommendedAlternatives.map((alt, i) => (
            <li
              key={i}
              className="flex items-start gap-3 py-2.5 px-3 rounded-xl bg-orange-50 border border-orange-100"
            >
              <ArrowRight size={14} className="mt-0.5 flex-shrink-0 text-orange-500" />
              <span className="text-stone-700 text-sm leading-relaxed">{alt}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* ── Citations ── */}
      <div className="bg-white rounded-2xl p-5 border border-orange-100 shadow-sm shadow-orange-900/5">
        <h3 className="flex items-center gap-2 text-sm font-semibold text-stone-500 mb-3 uppercase tracking-wide">
          <BookOpen size={15} className="text-stone-400" />
          Citations
        </h3>
        <ul className="space-y-2">
          {citations.map((c, i) => (
            <li key={i} className="flex items-center gap-3 text-sm">
              <span className="text-orange-600 font-mono text-xs bg-orange-50 px-2 py-0.5 rounded border border-orange-200">
                {c.excerptRef}
              </span>
              <span className="text-stone-500">{c.source}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
